openapi: 3.0.1
info:
  title: Maven Version Tool
  description: Get the latest stable version of a Maven package.
  version: "1.0.0"
servers:
  - url: http://localhost:8000
paths:
  /get-latest-maven-version:
    get:
      summary: Get latest stable Maven version
      operationId: getLatestMavenVersion
      parameters:
        - name: groupId
          in: query
          required: true
          schema:
            type: string
        - name: artifactId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Latest version found
          content:
            application/json:
              schema:
                type: object
                properties:
                  latest_version:
                    type: string
        "404":
          description: No version found
